<template>
<div>
  <Navbar />
  <transition name="fade" appear>
    <main> <!-- a wrapper for slot is needed -->
      <slot /> <!-- the content -->
    </main>
  </transition>
  <Footer />
</div>
</template>

<script>
import Navbar from '~/components/Navbar'
import Footer from '~/components/Footer'
export default {
  components: {
    Navbar,
    Footer
  },
  data: function () {
    return {
      loaded: false
    }
  },
  mounted() {
 // run after everything is in-place
      this.loaded = true
      console.log(this.loaded)
  }
}
</script>

<style>
.fade-enter-active {
  transition: opacity .5s;
}

.fade-enter {
  opacity: 0;
}

#loader-wrapper {

}
.hidden {
  display: none;
}

@keyframes ldio-gdj1e0m3fap {
  0% { background: #a976c3 }
  25% { background: #a976c3 }
  25.25% { background: #5f2a62 }
  100% { background: #5f2a62 }
}
.ldio-gdj1e0m3fap div {
  position: absolute;
  width: 160px;
  height: 160px;
  background: #5f2a62;
  animation: ldio-gdj1e0m3fap 1.2195121951219512s linear infinite;
}
.loadingio-spinner-blocks-d3i21bsne5i {
  width: 800px;
  height: 800px;
  display: inline-block;
  overflow: hidden;
  background: #5c95cf;
}
.ldio-gdj1e0m3fap {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gdj1e0m3fap div { box-sizing: content-box; }
/* generated by https://loading.io/ */


</style>